### ISSUE TITLE
fatal error C1083: Cannot open include file: 'zlib.h': No such file or directory

### ISSUE THREAD

**Issue by skipik** [lazyhamster/Observer#3]
Переставил студию заново и никак не могу понять, почему не получается собрать. Большая часть модулей отказывается собираться с ошибкой: fatal error C1083: Cannot open include file: 'zlib.h': No such file or directory. Что именно нужно поправить?

**Comment by skipik** [comment]
Можно закрыть. Сам виноват. Я совсем забыл про зависимости и это:
vcpkg install zlib:x86-windows zlib:x64-windows
vcpkg install bzip2:x86-windows bzip2:x64-windows
vcpkg install glib:x86-windows glib:x64-windows

**Comment by lazyhamster** [comment]
Ещё boost нужен, для модуля pst. Если нет отдельно собранного, то можно тоже через vcpkg поставить.
Хорошим руководством может служить файл appveyor.yml. Там как раз все нужные зависимости устанавливаются.
