### ISSUE TITLE
Неправильно работает с tar

### ISSUE THREAD

**Issue by ziceptor** [lazyhamster/Observer#4]
tar:
```
x32\
x32\bla-bla1.iso
x32\bla-bla2.iso
x32\bla-bla3.iso
```
При входе в tar автоматом отображается содержимое  iso. Ожидал увидеть структуру tar контейнера.

Observer 1.12.0
Far Manager, version 3.0.0.5485 x64
Win 10 Корп x64

**Comment by lazyhamster** [comment]
Плагин в tar не умеет. Но умеет находить iso по нестандартным смещениям. Поэтому он проигнорировал заголовок tar-а и открыл первый iso, который нашел в начале архива.

**Comment by ziceptor** [comment]
Как это исправить? Потенциально, можно потерять данные.

**Comment by lazyhamster** [comment]
Чего им теряться то? Архив не модифицируется. А если надо tar распаковать, то есть arclite, надо его только вручную выбрать по F11.

**Comment by ziceptor** [comment]
При текущем положении дел, пользователь увидит только часть содержимого и может так оказаться, что оно ему не надо будет. Удалит и похерит, то что не увидел. Как-то так.

**Comment by lazyhamster** [comment]
Логично. Но все же случай достаточно редкий, как по мне. Да и на все случаи жизни от невенимательности не застрахуешься. 
Если надо часто с tar-ами работать, то можно поменять приоритет плагинов, чтобы arclite первый файлы нюхал (самый простой вариант - убрать цифру 4 из имени файла 4Observer.dll). Такие коллизии всегда решаются настройкой приоритетов под себя, универсального решения нет.

**Comment by Kojoley** [comment]
Ситуацию можно улучшить если фар станет опрашивать плагины в два раунда: сначала с просьбой не использовать эвристики, и если неудачна - то уже с оными.

Observer в свою очередь может выводить в отображаемый псевдопуть оффсет (если он ненулевой, например `ISO@123456:\`), или корень псевдофс начинать с папки говорящей что это контейнер по оффсету.

**Comment by ziceptor** [comment]
А в настройках плагина можно указать, что бы в tar не совался?

**Comment by ziceptor** [comment]
>от невенимательности не застрахуешься

В данном случае не невнимательность.
То, что плагин умеет находить iso по нестандартным смещениям - хорошо. Но пусть тогда уж предупреждает.

Пока понизил приоритет, спасибо!

**Comment by lazyhamster** [comment]
> А в настройках плагина можно указать, что бы в tar не совался?

Сейчас нет. Но, в принципе, ничего не мешает добавить возможность указывать расширения файлов, которые нужно игорировать.

**Comment by lazyhamster** [comment]
Добавил для подобных случаев настройку. Можно указать расширения файлов, которые плагин будет игнорировать. Доступна в observer.ini.

**Comment by ziceptor** [comment]
Спасибо!
