### ISSUE TITLE
Windows Service command line args string can be longer than 255 chars

### ISSUE THREAD

**Issue by yurikus** [lazyhamster/Observer#5]
https://github.com/lazyhamster/Observer/blob/ef6a785b728b12a6f0327c648011910dbf495ae4/src/modules/msi/PackageStruct.h#L110

This array needs to be larger, otherwise I'm hitting the bug within [this MSI](https://snapshots.elastic.co/7.6.0-522a0451/downloads/beats/winlogbeat/winlogbeat-7.6.0-SNAPSHOT-windows-x86_64.msi)

**Comment by lazyhamster** [comment]
Problem should be fixed in 60b12c8be51bd34d44ce585240a3525e0e195517

**Comment by yurikus** [comment]
Thank you @lazyhamster! Can we do a build/release please?

**Comment by skipik** [comment]
https://www.dropbox.com/s/cutv9xoc8vvo0dc/Observer_Far3_x64_1.12.0.rar?dl=1
https://www.dropbox.com/s/g375g0k4pn6p893/Observer_Far3_x86_1.12.0.rar?dl=1

**Comment by lazyhamster** [comment]
Builds are automatic with AppVeyor. You can get latest build here: https://dl.bintray.com/lazyhamster/FAR-Plugins

**Comment by yurikus** [comment]
LGTM
