### ISSUE TITLE
Setup Factory 9.0

### ISSUE THREAD

**Issue by Puyodead1** [lazyhamster/Observer#9]
I've been trying to unpack multiple exe installers that use Setup Factory, they appear to use Setup Factory version 9.0 as the xml contains `Setup Factory 9 Run-time`. Only one of the installers was able to be opened which used SF 9.5. Is this version of SF supported? I haven't been able to find anything else for unpacking these files.

**Comment by lazyhamster** [comment]
If you can share installer files I'll take a look.

**Comment by Puyodead1** [comment]
> If you can share installer files I'll take a look.

Sure, here is one of the installers: https://www.dropbox.com/s/ydqyvkaiwnyjfm5/setup.exe
Thank you in advance.

**Comment by lazyhamster** [comment]
Problem should be fixed in b72a19ffe705147d26919a3db7a3513476cdcd8a

**Comment by Puyodead1** [comment]
> Problem should be fixed in [b72a19f](https://github.com/lazyhamster/Observer/commit/b72a19ffe705147d26919a3db7a3513476cdcd8a)

Works perfectly, thank you so much!
